### ISSUE TITLE
Resource Check unsuccessful while using gitlab-merge-request-resource 

### ISSUE THREAD

**Issue by krajdeep** [samcontesse/gitlab-merge-request-resource#32]
This is my resource configuration 

resource_types:
- name: merge-request
  type: docker-image
  source:
    repository: samcontesse/gitlab-merge-request-resource
    tag: latest
resources:
- name: merge-request
  type: merge-request
  source:
    uri: ((using an https repository url))
    private_token: ((personal access token of the user))
jobs:
- name: build
  public: true
  plan:
  - get: ((another resource))
  - get: merge-request
    trigger: true
  - put: merge-request
    params:
      repository: merge-request
      status: running
  - task: build
    config:
        platform: linux
        image_resource:
            type: registry-image
            source: ((source for the image))
        inputs:
          - name: ((another resource))
        run: ((script))
  on_failure:
    put: merge-request
    params:
      repository: merge-request
      status: failed
  on_success:
    put: merge-request
    params:
      repository: merge-request
      status: success
      labels: ['compilation', 'stage']

While concourse is checking the resource merge-request it is giving the below error

run check step: run check step: check: resource script '/opt/resource/check []' failed: exit status 2

stderr:
panic: runtime error: index out of range [3] with length 0

goroutine 1 [running]:
github.com/samcontesse/gitlab-merge-request-resource.(*Source).GetProjectPath(0xc0000ba000, 0xc0000e0000, 0x2e)
	/go/src/github.com/samcontesse/gitlab-merge-request-resource/models.go:45 +0xa0
main.main()
	/go/src/github.com/samcontesse/gitlab-merge-request-resource/check/cmd/main.go:34 +0x37c

How should I solve this error and proceed ?

**Comment by samcontesse** [comment]
Hello @krajdeep,

It looks that your `uri` has something to do with the error. Can you share the structure of your `uri` ? You can replace sensitive information but I would need the whole form to see if I can be parsed correctly.

Thanks

**Comment by krajdeepr** [comment]
Hello sam, 
yeah it was a problem from the uri side my bad sorry but I have another concern, presently we are getting a single status of all the jobs under external in the merge request page, can we show the status of each job from the pipeline separately ?

**Comment by krajdeep** [comment]
Hello @samcontesse,
yeah it was a problem from the uri side my bad sorry but I have another concern, presently we are getting a single status of all the jobs under external in the merge request page, can we show the status of each job from the pipeline separately ?

Thanks

**Comment by samcontesse** [comment]
@krajdeep Can you post a screenshot of what you see ? There should

**Comment by samcontesse** [comment]
No news — good news? Could you find the solution @krajdeep?

**Comment by samcontesse** [comment]
Closing due to inactivity
